BOARD_TAG     = uno
ARDUINO_PORT  = /dev/ttyACM*
ARDUINO_LIBS  =

ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/local
AVR_TOOLS_DIR = /usr

AM_HOME       = $(HOME)/downloads/Arduino-Makefile
ARDMK_PATH    = $(AM_HOME)/bin

include $(AM_HOME)/arduino-mk/Arduino.mk
